function DataPatients = importPatients(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DATAPATIENTS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  DATAPATIENTS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  DataPatients = importfile("C:\Users\js4378\OneDrive - Yale University\Elbows  Lattanza\RadialHead50\DataPatients.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Feb-2024 15:12:32

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Case", "Age", "Sex", "Ethnicity", "Hispanic"];
opts.VariableTypes = ["double", "double", "categorical", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Sex", "Ethnicity", "Hispanic"], "EmptyFieldRule", "auto");

% Import the data
DataPatients = readtable(filename, opts);

end